### ISSUE TITLE
Properly launch off of PyPI

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-us-data#23]
At the moment, due to either an issue with Git tags or with `setuptools_scm` (or both), we are unable to properly upload distributions to PyPI.

**Comment by nikhilwoodruff** [comment]
Fixed thanks to your PR!

**Comment by MaxGhenis** [comment]
Sort of right? Shouldn't we be using standard version numbers?

https://pypi.org/project/policyengine-us-data/#history
<img width="793" alt="image" src="https://github.com/user-attachments/assets/6c8ca6fd-323d-4dbe-8944-42649907770e">
