### ISSUE TITLE
Add versioning similar to other repos

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-us-data#30]
This requires both a changelog and an automatic git tagging feature.

The issue here is that `setuptools_scm` will only follow fully semantic updating if on a `release-` branch ([link](https://setuptools-scm.readthedocs.io/en/latest/usage/)), even when using its built-in semantic versioning setup, otherwise it will always append `devX` to the branch version. I've yet to find any way to override this behavior.

Getting this working properly would allow the package to be imported via `pip` following the standard scheme in use elsewhere, preventing the need to install manually via git when using, e.g., `policyengine-us`.

**Comment by MaxGhenis** [comment]
See also #15
