### ISSUE TITLE
PolicyEngine US fails to run in GitHub Actions

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us-data#5]
Struggling to reproduce this, as it works fine on my machine and Google Cloud. Here's the failing [action](https://github.com/PolicyEngine/policyengine-us-data/actions/runs/10682222270/job/29607551861?pr=4). I first noticed it after merging https://github.com/PolicyEngine/policyengine-us-data/pull/2 when the PR's action passed but the main branch action failed (with no differences in code, AFAICT).

@anth-volk could you try to reproduce by cloning this repo and running `make install` and `make data`? Thanks!

**Comment by anth-volk** [comment]
When running the above, I do run into the same issue. I'm currently looking into it to see if I can figure out what might be the cause.

**Comment by anth-volk** [comment]
The furthest I've been able to get so far is that it appears that when the enhanced CPS attempts to generate its loss matrix, none of the state-related variables are correctly encoded as `Enum` types, meaning that `decode_to_str()` is not an available method, causing the build to crash at the point at which it's called while calculating SNAP. Does the model ever treat state code or name as an input, and in the process, perhaps not instantiate itself correctly as an `Enum`?

**Comment by nikhilwoodruff** [comment]
Aha yep also confirmed I can now reproduce it after reinstalling US and Core!
