### ISSUE TITLE
Assign take-up random numbers

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us-data#84]
Currently, we assign random values in policyengine-us variable formulas when determining take-up. By moving that to the dataset generation (e.g. adding a variable for `snap_takeup_rand` - these should be separate per benefit), we can make the microsimulation itself deterministic.

The stochastic microsimulations causes discrepancies across subsetting procedures as well.

**Comment by nikhilwoodruff** [comment]
I don't think we should do this: it'd mean that any time we add a new random number usage in a country package anywhere, we'd need to rerun the dataset creation.

**Comment by nikhilwoodruff** [comment]
Instead, here's an example of a `random(entity)` function that would preserve determinism by the entity ID:

```python

def random(population):
    """
    Generate random values for each entity in the population.

    Args:
        population: The population object containing simulation data.

    Returns:
        np.ndarray: Array of random values for each entity.
    """
    # Initialize count of random calls if not already present
    if not hasattr(population.simulation, "count_random_calls"):
        population.simulation.count_random_calls = 0
    population.simulation.count_random_calls += 1

    # Get known periods or use default calculation period
    known_periods = population.simulation.get_holder(
        f"{population.entity.key}_id"
    ).get_known_periods()
    period = (
        known_periods[0]
        if known_periods
        else population.simulation.default_calculation_period
    )

    # Get entity IDs for the period
    entity_ids = population(f"{population.entity.key}_id", period)

    # Generate random values for each entity
    values = np.array(
        [
            np.random.default_rng(
                seed=id * 100 + population.simulation.count_random_calls
            ).random()
            for id in entity_ids
        ]
    )

    return values
```

**Comment by MaxGhenis** [comment]
I still think it would be more transparent to include the values themselves to make the calculator as clearly deterministic as possible.

**Comment by nikhilwoodruff** [comment]
OK I think this is now implemented, under your way.
